// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `start_client`

Future<void> startServer({
  required int port,
  required ReceiverKvmEvent receiver,
}) => RustLib.instance.api.crateApiNetworkStartServer(
  port: port,
  receiver: receiver,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Receiver < KvmEvent >>>
abstract class ReceiverKvmEvent implements RustOpaqueInterface {}
